= istio-java-api

A project to generate a Java API for https://istio.io[Istio]'s domain allowing, in particular, the generation of Istio deployment
descriptors. This project is inspired by https://github.com/fabric8io/kubernetes-model[Fabric8's kubernetes-model] and relies on
the same approach: a Go program uses Go reflection to generate a http://json-schema.org[JSON Schema] which is then used by
https://github.com/joelittlejohn/jsonschema2pojo[jsonschema2pojo] to generate Java classes, enriched by annotations
(https://github.com/fasterxml/jackson[Jackson] and https://jcp.org/en/jsr/detail?id=380[Bean Validation - JSR 380] notably,
though custom annotations can also be used). Jackson is then used to output JSON or YAML representation of the Java objects when
needed.

= Usage

Please take a look at the tests in `istio-model/src/test/java` to see how the API can be used. You can also take a look at the
https://github.com/metacosm/istio-test-dsl project which demonstrates an end-to-end scenario using the Fabric8 OpenShift adapter
and this API to send Istio artifacts to a running OpenShift cluster configured on which Istio is set up.

= Building instructions

If you only want to build the current version of the API and don't intend on modifying how the JSON Schema is generated, you can build simply using `mvn clean install` as the project contains a pre-generated version of the schema. If you need to re-generate the classes from a newer version of the API, since the build relies on Go introspection, you will need to set up a Go programming environment.

== Initial setup

In particular, you will need to https://golang.org/doc/install[install Go] and check the code for this project within your `$GOPATH/src` hierarchy:

```bash
cd $GOPATH/src
git clone git@github.com:snowdrop/istio-java-api.git
cd istio-java-api
```

== Building the Java API

Run `make`. This will build the `generate` command line tool from Go and then run it to generate a JSON Schema in
`istio-model/src/main/resources/schema/istio-schema.json`. A Maven build is then issued using the `jsonschema2pojo` Maven plugin
to generate Java classes in `istio-model/target/generated-sources` and generate a Jar file containing the compiled version of
these classes along with the JSON schema, ready to be used.

You can clean everything using `make clean`, only generate the schema using `make schema` or only generate the Java classes (assuming a schema already exists) using `mvn clean install`.

You can also to re-generate the properties file that is used to determine which
https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Kubernetes Custom Resource Definitions (CRDs)]
are specified by Istio. This file is located at `istio-common/src/main/resources/crd_list.properties` and can be generated using
`make crd`. Right now, though, this command requires installing the
https://docs.openshift.org/latest/cli_reference/get_started_cli.html[OpenShift Client] and an active administrative connection
(via `oc login`) to an OpenShift cluster on which Istio is installed.

