package me.snowdrop.istio.api.mesh.v1alpha1;

public enum Resource {

    /**
     * Set to only receive service entries that are generated by the platform.
     * These auto generated service entries are combination of services and endpoints
     * that are generated by a specific platform e.g. k8
     */
    SERVICE_REGISTRY(0);

    private final int intValue;

    Resource(int intValue) {
        this.intValue = intValue;
    }

    public int value() {
        return intValue;
    }
}
